'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ArrowRight,ArrowUpRight,BookOpen,Boxes,Braces,Check,CheckCircle2,ChevronDown,ChevronRight,Clock3,Code2,Database,ExternalLink,FileCode2,Flame,FolderGit2,GraduationCap,LayoutDashboard,Library,Lightbulb,Loader2,Menu,Network,Play,RotateCcw,Search,Send,Settings2,ShieldCheck,Sparkles,Square,Target,Terminal,Upload,X} from 'lucide-react';
import {api,post,login} from '@/lib/api';
import type {Track,Module,Lesson,Exercise,Progress,Source} from '@/lib/types';

const Editor=dynamic(()=>import('@monaco-editor/react'),{ssr:false,loading:()=> <div className="editor-loading">Loading code editor…</div>});
const EMPTY:Progress={skills:[],read_lessons:[],recent_jobs:[]};
const trackIcon=(id:string)=>id==='ontology'?Network:id==='spark'?Flame:id==='statistics'?Target:Database;
function Sources({items}:{items:Source[]}){return <div className="sources">{items.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={14}/></a>)}</div>}
function Md({children}:{children:string}){return <div className="markdown"><Markdown remarkPlugins={[remarkGfm]}>{children}</Markdown></div>}

export default function Home(){
  const [tracks,setTracks]=useState<Track[]>([]),[allExercises,setAllExercises]=useState<Exercise[]>([]),[progress,setProgress]=useState<Progress>(EMPTY);
  const [view,setView]=useState('dashboard'),[trackId,setTrackId]=useState('ontology'),[selectedModule,setModule]=useState<Module|null>(null),[selectedLesson,setLesson]=useState<Lesson|null>(null),[challenge,setChallenge]=useState<Exercise|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[mobile,setMobile]=useState(false),[email,setEmail]=useState(''),[role,setRole]=useState('learner');
  const refresh=useCallback(()=>api<Progress>('/progress').then(setProgress),[]);
  useEffect(()=>{Promise.all([api('/tracks'),api('/exercises'),api('/progress'),api('/me')]).then(([c,e,p,u])=>{setTracks(c.tracks);setAllExercises(e);setProgress(p);setEmail(u.email);setRole(u.role)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const navigate=(v:string)=>{setView(v);setChallenge(null);setLesson(null);setMobile(false);setSearch('')};
  const openTrack=(id:string)=>{setTrackId(id);navigate('track')};
  const openModule=async(mid:string)=>{try{setModule(await api('/modules/'+mid));setLesson(null);setView('module')}catch(e){setError((e as Error).message)}};
  const openExercise=async(eid:string)=>{try{setChallenge(await api('/exercises/'+eid));setView('challenge')}catch(e){setError((e as Error).message)}};
  const openLesson=async(lid:string)=>{try{setLesson(await api('/lessons/'+lid));setView('lesson')}catch(e){setError((e as Error).message)}};
  const selectedTrack=tracks.find(t=>t.id===trackId);
  const passed=progress.skills.filter(s=>s.state.startsWith('passed')).length;
  const due=progress.skills.filter(s=>s.due);
  const nextExercise=allExercises.find(e=>!progress.skills.some(s=>s.exercise_id===e.id&&s.state.startsWith('passed')));
  const trackProgress=(id:string)=>{const ids=tracks.find(t=>t.id===id)?.modules.map(m=>m.id)||[];const es=allExercises.filter(e=>ids.includes(e.module_id));const n=es.filter(e=>progress.skills.some(s=>s.exercise_id===e.id&&s.state.startsWith('passed'))).length;return {n,total:es.length,percent:es.length?Math.round(n/es.length*100):0}};
  const title=view==='dashboard'?'Your learning workspace':view==='track'?selectedTrack?.title:view==='module'?selectedModule?.title:view==='lesson'?selectedLesson?.title:view==='challenge'?challenge?.title:view==='practice'?'Practice library':view==='projects'?'Build something that connects':view==='review'?'Your review queue':view==='references'?'Official reference library':'Content review';
  if(loading)return <main className="boot"><Network size={36}/><h1>Graphlab</h1><Loader2 className="spin"/><p>Opening your workspace…</p></main>;
  if(!tracks.length)return <main className="login"><Network size={40}/><h1>Welcome to Graphlab</h1><p>Your workspace for ontology engineering and Apache Spark.</p><button className="primary" onClick={()=>login().catch(e=>setError(e.message))}>Sign in to your workspace <ArrowRight size={16}/></button><p className="error">{error}</p><p className="muted">Access is invitation-only. If the service is unavailable, try again shortly.</p></main>;
  return <div className={'app '+(view==='challenge'?'challenge-app':'')}>
    <aside className={'sidebar '+(mobile?'mobile-open':'')}>
      <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('dashboard')}}><span className="brand-icon"><Network size={22}/></span>graphlab<span className="brand-period">.</span></a>
      <div className="workspace-label"><span className="workspace-avatar">G</span><span>Learning workspace<small>Personal workspace</small></span><ChevronDown size={14}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav>{[[LayoutDashboard,'dashboard','Overview'],[Code2,'practice','Practice'],[FolderGit2,'projects','Projects'],[RotateCcw,'review','Review queue'],[Library,'references','References']].map(([Icon,id,label])=>{const I=Icon as typeof Network;return <button key={id as string} className={'nav-item '+(view===id?'active':'')} onClick={()=>navigate(id as string)}><I size={19}/>{label as string}{id==='review'&&due.length>0&&<span className="nav-count">{due.length}</span>}</button>})}</nav>
      <div className="nav-label track-nav-heading">YOUR TRACKS <span>{tracks.length}</span></div>
      <nav>{tracks.map(t=>{const I=trackIcon(t.id);return <button className={'nav-item '+(view==='track'&&trackId===t.id?'active':'')} key={t.id} onClick={()=>openTrack(t.id)}><I size={18}/><span>{t.title}</span>{t.status==='planned'&&<span className="soon-mini">Soon</span>}</button>})}</nav>
      <div className="sidebar-bottom"><div className="sidebar-note"><BookOpen size={19}/><strong>Learn it. Build it. Know it.</strong><p>Small steps, working code, deeper understanding.</p></div>{role==='admin'&&<button className="nav-item" onClick={()=>navigate('author')}><Settings2 size={18}/>Author preview</button>}<div className="profile"><span className="avatar">{email[0]?.toUpperCase()}</span><div><strong>{email.split('@')[0]}</strong><small>Personal learning space</small></div></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view==='dashboard'?'Overview':view==='challenge'?'Practice':view.charAt(0).toUpperCase()+view.slice(1)}</strong></div><div className="topbar-right"><span className="preview-pill">Private preview</span><span className="avatar small">{email[0]?.toUpperCase()}</span></div></header>
    {error&&<div className="error-banner" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
    {view==='challenge'&&challenge?<Challenge key={challenge.id} exercise={challenge} onBack={()=>{setView('practice');setChallenge(null)}} onProgress={refresh}/>:<main className="main-content">
      <div className="page-heading"><div><div className="eyebrow">{view==='dashboard'?'A LITTLE PRACTICE. A DEEPER UNDERSTANDING.':view==='track'?'LEARNING PATH':'YOUR LEARNING SPACE'}</div><h1>{title}</h1><p>{view==='dashboard'?'Pick up where you left off, or explore something new.':view==='practice'?'Real problems. Executable solutions. Feedback that helps you improve.':view==='track'?selectedTrack?.description:''}</p></div>{view==='dashboard'&&<button className="outline" onClick={()=>navigate('practice')}>Explore exercises<ArrowUpRight size={16}/></button>}</div>
      {view==='dashboard'&&<>
        <div className="overview-grid"><section className="continue-panel"><div className="continue-top"><span className="pill light"><Network size={14}/>ONTOLOGY ENGINEERING</span><span className="tiny-label">YOUR NEXT STEP</span></div><h2>{nextExercise?.title||'All caught up. Keep your skills sharp.'}</h2><p>{nextExercise?nextExercise.objectives[0]:'Review an earlier challenge using a fresh approach.'}</p><div className="continue-footer"><button className="lime-button" onClick={()=>nextExercise?openExercise(nextExercise.id):navigate('review')}>{progress.recent_jobs.length?'Continue learning':'Start learning'}<ArrowRight size={17}/></button><span><Clock3 size={15}/>{nextExercise?.minutes||15} min practice</span></div><div className="network-motif" aria-hidden="true"><Network size={132} strokeWidth={.8}/></div></section>
        <section className="progress-panel"><div className="section-mini"><Target size={18}/><h3>Your progress</h3></div><div className="stat-number">{passed}<span>exercises completed</span></div><div className="stat-bottom"><div><strong>{progress.read_lessons.length}</strong><span>Lessons read</span></div><div><strong>{due.length}</strong><span>Ready to review</span></div></div><button className="text-button" onClick={()=>navigate('review')}>View your review queue<ArrowRight size={15}/></button></section></div>
        <div className="section-heading"><div><h2>Your learning tracks</h2><p>Follow a path from first principles to practical projects.</p></div><span className="count-label">2 active tracks</span></div>
        <div className="track-grid">{tracks.filter(t=>t.status!=='planned').map(t=>{const I=trackIcon(t.id),p=trackProgress(t.id);return <button key={t.id} className={'track-card '+t.id} onClick={()=>openTrack(t.id)}><div className="track-card-top"><span className="track-icon"><I size={27}/></span><span className="pill">{t.id==='ontology'?'PRIMARY TRACK':'GROWING TRACK'}</span></div><h3>{t.title}</h3><p>{t.description}</p><div className="track-meta"><span><BookOpen size={15}/>{t.modules.length} modules</span><span><Code2 size={15}/>{p.total} exercises</span></div><div className="progress-caption"><span>{p.n===0?'Ready when you are':`${p.n} exercises completed`}</span><strong>{p.percent}%</strong></div><div className="progress-track"><div style={{width:p.percent+'%'}}/></div><div className="card-link">Explore track<ArrowRight size={17}/></div></button>})}</div>
        <div className="section-heading"><div><h2>More paths, on the horizon</h2><p>A foundation for everything you want to learn next.</p></div></div><div className="planned-grid">{tracks.filter(t=>t.status==='planned').map(t=>{const I=trackIcon(t.id);return <button className="planned-card" onClick={()=>openTrack(t.id)} key={t.id}><I size={23}/><div><h3>{t.title}</h3><span>Curriculum outline</span></div><span className="pill">Planned</span></button>})}</div>
        <section className="method-strip"><GraduationCap size={27}/><div><strong>Understanding comes from doing.</strong><p>Learn a concept, test it in a real environment, then apply it to a new problem.</p></div><span>Learn<ChevronRight size={14}/>Practice<ChevronRight size={14}/>Build<ChevronRight size={14}/>Review</span></section>
      </>}
      {view==='track'&&selectedTrack&&<>{selectedTrack.status==='planned'?<div className="planned-outline"><span className="pill">Planned track</span><h2>A look at the path ahead</h2><p>This track is not open for enrollment yet. Here is the planned progression.</p>{selectedTrack.topics?.map((t,i)=><div className="outline-row" key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3></div>)}</div>:<><div className="track-summary"><span><BookOpen size={18}/>{selectedTrack.modules.length} modules</span><span><Code2 size={18}/>{trackProgress(selectedTrack.id).total} exercises</span><span><ShieldCheck size={18}/>Official documentation</span><span>Fundamentals → Advanced</span></div><div className="module-list">{selectedTrack.modules.map((m,i)=>{const read=m.lessons.filter(l=>progress.read_lessons.includes(l.id)).length;return <button className="module-row" key={m.id} onClick={()=>openModule(m.id)}><span className="module-number">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{m.level}</span><h3>{m.title}</h3><p>{m.description}</p><div className="track-meta"><span>{m.lessons.length} lessons</span><span>{allExercises.filter(e=>e.module_id===m.id).length} exercises</span></div></div><span className="module-read">{read}/{m.lessons.length} read</span><ChevronRight size={20}/></button>})}</div></>}</>}
      {view==='module'&&selectedModule&&<div className="module-detail"><section><h2>Understand the concepts</h2>{selectedModule.lessons.map((l,i)=><button className="lesson-row" key={l.id} onClick={()=>openLesson(l.id)}>{progress.read_lessons.includes(l.id)?<CheckCircle2 className="success" size={20}/>:<span className="lesson-index">{i+1}</span>}<div><h3>{l.title}</h3><span>{l.minutes} min · Lesson</span></div><ArrowUpRight size={17}/></button>)}<h2 className="spaced-heading">Put it into practice</h2>{selectedModule.exercises?.map(e=><ExerciseRow key={e.id} e={e} progress={progress} open={openExercise}/>)}</section><aside className="reference-panel"><h3>Learning objectives</h3><p>{selectedModule.description}</p><h3>Go to the source</h3><Sources items={selectedModule.sources}/><div className="note"><Lightbulb size={20}/><p>Read the example, predict what will happen, then run it. Explaining the difference is part of the practice.</p></div></aside></div>}
      {view==='lesson'&&selectedLesson&&<div className="lesson-layout"><article className="lesson-paper"><Md>{selectedLesson.body||''}</Md><button className="primary" onClick={async()=>{await post('/lessons/'+selectedLesson.id+'/read');await refresh()}}>{progress.read_lessons.includes(selectedLesson.id)?<><Check size={17}/>Marked as read</>:<>Mark lesson as read<Check size={17}/></>}</button></article><aside className="reference-panel"><h3>Official references</h3><Sources items={selectedLesson.sources||[]}/><h3>Apply this lesson</h3>{allExercises.filter(e=>e.module_id===(selectedLesson as any).module_id).slice(0,3).map(e=><button className="lesson-practice" key={e.id} onClick={()=>openExercise(e.id)}>{e.title}<ArrowRight size={16}/></button>)}<p className="muted">Reading and demonstrated mastery are tracked separately.</p></aside></div>}
      {view==='practice'&&<><div className="filter-bar"><div className="search-field"><Search size={18}/><input aria-label="Search exercises" placeholder="Search by concept, exercise, or runtime…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter track" value={trackId} onChange={e=>setTrackId(e.target.value)}><option value="all">All tracks</option><option value="ontology">Ontology engineering</option><option value="spark">Apache Spark</option></select></div><div className="exercise-list">{allExercises.filter(e=>(trackId==='all'||e.module_id.startsWith(trackId==='ontology'?'o':'s'))&&`${e.title} ${e.runner} ${e.objectives.join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(e=><ExerciseRow key={e.id} e={e} progress={progress} open={openExercise}/>)}</div></>}
      {view==='review'&&<><div className="review-summary"><RotateCcw size={25}/><div><h2>{due.length?'Time to strengthen what you know':'Your next review will appear here'}</h2><p>Revisit skills after 1, 7, and 21 days. Assisted exercises remain worth practicing independently.</p></div></div>{allExercises.filter(e=>progress.skills.some(s=>s.exercise_id===e.id&&(s.due||s.state==='passed_with_assistance'))).map(e=><ExerciseRow key={e.id} e={e} progress={progress} open={openExercise}/>)}</>}
      {view==='references'&&<div className="reference-grid">{tracks.filter(t=>t.status!=='planned').map(t=><section className="reference-card" key={t.id}><h2>{t.title}</h2>{Array.from(new Map(t.modules.flatMap(m=>m.sources).map(s=>[s.url,s])).values()).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><BookOpen size={18}/><div><strong>{s.title}</strong><span>{new URL(s.url).hostname}</span></div><ExternalLink size={16}/></a>)}</section>)}</div>}
      {view==='projects'&&<Projects/>}{view==='author'&&<Author/>}
      <footer className="footer"><span><Network size={15}/>Graphlab</span><span>Built around official sources. Learned through practice.</span></footer>
    </main>}</div>
  </div>
}

function ExerciseRow({e,progress,open}:{e:Exercise;progress:Progress;open:(id:string)=>void}){const p=progress.skills.find(s=>s.exercise_id===e.id);return <button className="exercise-row" onClick={()=>open(e.id)}><span className={'exercise-symbol '+(p?'done':'')}>{p?<Check size={19}/>:<Code2 size={19}/>}</span><div><h3>{e.title}</h3><span>{e.runner.toUpperCase()} · {e.mode==='assessment'?'Checkpoint':e.mode==='guided'?'Guided lab':'Independent practice'} · {e.minutes} min</span></div><span className={'difficulty '+e.difficulty.toLowerCase()}>{e.difficulty}</span><ChevronRight size={17}/></button>}

function Challenge({exercise:e,onBack,onProgress}:{exercise:Exercise;onBack:()=>void;onProgress:()=>Promise<unknown>}){
  const [files,setFiles]=useState(e.starter),[file,setFile]=useState(Object.keys(e.starter)[0]),[revision,setRevision]=useState<number>(),[saveState,setSaveState]=useState('Loading draft…');
  const [mode,setMode]=useState(e.mode==='assessment'?'assessment':e.mode==='guided'?'guided':'practice'),[tab,setTab]=useState('problem'),[resultTab,setResultTab]=useState('feedback'),[job,setJob]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [hints,setHints]=useState<string[]>([]),[tutorOpen,setTutorOpen]=useState(false),[question,setQuestion]=useState(''),[tutorText,setTutorText]=useState(''),[tutorBusy,setTutorBusy]=useState(false),[assisted,setAssisted]=useState(false),[answers,setAnswers]=useState<Record<string,string>>({}),[solution,setSolution]=useState<any>(null);
  const ready=useRef(false),version=useRef<number|undefined>(undefined),timer=useRef<ReturnType<typeof setTimeout>|null>(null),latest=useRef(files),saving=useRef(Promise.resolve());
  useEffect(()=>{api('/workspaces/'+e.id).then(w=>{setFiles(w.files);latest.current=w.files;setRevision(w.revision);version.current=w.revision;setAssisted(w.assisted);ready.current=true;setSaveState('All changes saved')}).catch(x=>setError(x.message));return()=>{if(timer.current)clearTimeout(timer.current)}},[e.id]);
  const save=useCallback(async(next:Record<string,string>)=>{saving.current=saving.current.catch(()=>{}).then(async()=>{setSaveState('Saving…');const w=await api('/workspaces/'+e.id,{method:'PUT',body:JSON.stringify({files:next,revision:version.current})});version.current=w.revision;setRevision(w.revision);setSaveState('All changes saved')});try{await saving.current}catch(x){setSaveState('Not saved');setError((x as Error).message);throw x}},[e.id]);
  const change=(value:string)=>{const next={...latest.current,[file]:value};latest.current=next;setFiles(next);setSaveState('Unsaved changes');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>save(next).catch(()=>{}),650)};
  useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;let alive=true;const poll=setInterval(async()=>{try{const j=await api('/jobs/'+job.id);if(!alive)return;setJob(j);if(!['queued','running'].includes(j.status)){setBusy(false);await onProgress()}}catch(x){setError((x as Error).message);setBusy(false)}},1000);return()=>{alive=false;clearInterval(poll)}},[job?.id,job?.status,onProgress]);
  const execute=async(kind:string)=>{setBusy(true);setError('');setResultTab('feedback');try{if(timer.current)clearTimeout(timer.current);await save(latest.current);const j=await api(kind,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({exercise_id:e.id,files:latest.current,mode,answers})});setJob(await api('/jobs/'+j.id));if(!['queued','running'].includes(j.status))setBusy(false)}catch(x){setError((x as Error).message);setBusy(false)}};
  const getHint=async()=>{try{const h=await post(`/exercises/${e.id}/hints/${hints.length}`);setHints([...hints,h.hint]);setAssisted(true)}catch(x){setError((x as Error).message)}};
  const askTutor=async()=>{setTutorBusy(true);try{const r=await post('/tutor/messages',{exercise_id:e.id,question,code:files[file]});setTutorText(r.answer);if(r.available)setAssisted(true)}catch(x){setTutorText((x as Error).message)}finally{setTutorBusy(false)}};
  const language=file.endsWith('.py')?'python':file.endsWith('.json')?'json':file.endsWith('.rq')?'sparql':'turtle';
  const output=job?.feedback?.output;
  return <section className="challenge"><div className="challenge-header"><button className="text-button" onClick={async()=>{try{if(timer.current)clearTimeout(timer.current);await save(latest.current);onBack()}catch{}}}>← Back to practice</button><div><span className="difficulty">{e.difficulty}</span><span className="runtime-label">{e.runner.toUpperCase()}</span></div></div><div className="challenge-title"><h1>{e.title}</h1><div className="challenge-actions"><select aria-label="Learning mode" disabled={busy} value={mode} onChange={x=>setMode(x.target.value)}><option value="guided">Guided</option><option value="practice">Practice</option><option value="assessment">Assessment</option></select><button className={'outline '+(tutorOpen?'selected':'')} disabled={mode==='assessment'} onClick={()=>setTutorOpen(!tutorOpen)}><Sparkles size={16}/>Tutor</button></div></div>
    <div className={'challenge-panels '+(tutorOpen?'with-tutor':'')}><section className="problem-panel"><div className="tab-bar">{['problem','data','references'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t.charAt(0).toUpperCase()+t.slice(1)}</button>)}</div><div className="problem-content">{tab==='problem'?<><div className="exercise-meta"><Clock3 size={14}/>{e.minutes} minutes <span>·</span> Version {e.version}</div><Md>{e.statement}</Md><h3>Requirements</h3><ul className="requirements">{e.requirements.map(r=><li key={r}>{r}</li>)}</ul>{e.questions?.map(q=><fieldset key={q.id}><legend>{q.prompt}</legend>{q.options.map(o=><label className="answer-option" key={o}><input type="radio" name={q.id} value={o} checked={answers[q.id]===o} onChange={()=>setAnswers({...answers,[q.id]:o})}/>{o}</label>)}</fieldset>)}{mode!=='assessment'&&<div className="hints"><h3><Lightbulb size={18}/>Need a nudge?</h3>{hints.map((h,i)=><div className="hint" key={i}><strong>Hint {i+1}</strong><p>{h}</p></div>)}<button className="outline" disabled={hints.length>=3} onClick={getHint}>{hints.length>=3?'All hints revealed':'Reveal next hint'}</button><button className="text-button solution-button" onClick={async()=>{try{setSolution(await post(`/exercises/${e.id}/solution`));setAssisted(true)}catch(x){setError((x as Error).message)}}}>Reveal solution</button>{solution&&<div className="solution"><p>{solution.explanation}</p>{Object.entries(solution.files).map(([name,text])=><div key={name}><strong>{name}</strong><pre>{text as string}</pre></div>)}</div>}</div>}</>:tab==='data'?<>{e.fixtures.map(f=><div key={f.name}><h3>{f.name}</h3><pre className="dataset">{f.data}</pre></div>)}<p className="muted">Submit also checks additional datasets against the stated requirements.</p></>:<><h3>Go to the source</h3><Sources items={e.sources}/></>}</div></section>
    <section className="code-panel"><div className="editor-toolbar"><div className="file-tabs">{Object.keys(files).map(f=><button className={file===f?'selected':''} onClick={()=>setFile(f)} key={f}><FileCode2 size={14}/>{f}</button>)}</div><div className="editor-tools"><label className="icon-button" title="Import file"><Upload size={16}/><input type="file" className="sr-only" accept=".ttl,.rq,.py,.json" onChange={async ev=>{const f=ev.target.files?.[0];if(f){if(f.size>200000){setError('File exceeds 200 KB');return}change(await f.text())}}}/></label><button className="icon-button" title="Reset current file" onClick={()=>change(e.starter[file])}><RotateCcw size={16}/></button></div></div><div className="editor"><Editor height="100%" language={language} theme="vs-dark" value={files[file]} onChange={v=>ready.current&&change(v||'')} options={{fontSize:14,fontFamily:'Consolas, monospace',minimap:{enabled:false},padding:{top:20},scrollBeyondLastLine:false,automaticLayout:true,wordWrap:'on',tabSize:2,ariaLabel:`Code editor for ${file}`}}/></div><div className="editor-status"><span>{saveState}</span><span>{assisted?'Assistance used · fresh variant needed for mastery':'Independent attempt'}</span></div><div className="run-toolbar"><span><Terminal size={15}/>Isolated execution</span><div>{busy?<button className="outline" onClick={async()=>{if(job)setJob({...job,...await post('/jobs/'+job.id+'/cancel')})}}><Square size={14}/>Cancel</button>:<button className="outline" onClick={()=>execute('/runs')} disabled={!ready.current}><Play size={15}/>Run examples</button>}<button className="primary" disabled={busy||!ready.current} onClick={()=>execute('/submissions')}>{busy?<Loader2 size={16} className="spin"/>:<Send size={15}/>}Submit</button></div></div>
    <div className="results"><div className="tab-bar">{['feedback','results','plan'].map(t=><button key={t} className={resultTab===t?'selected':''} onClick={()=>setResultTab(t)}>{t.charAt(0).toUpperCase()+t.slice(1)}</button>)}{job&&<span className={'job-status '+job.status}>{job.status.replaceAll('_',' ')}</span>}</div><div className="result-content" aria-live="polite">{error&&<div className="error">{error}</div>}{!job?<div className="empty-results"><Terminal size={25}/><p>Your results will appear here.</p><span>Run examples to explore. Submit to check your solution.</span></div>:resultTab==='feedback'?<><p>{job.feedback?.message||(busy?'Your exercise is being processed…':'')}</p>{job.feedback?.checks?.map((c:any,i:number)=><div className={'check-row '+(c.passed?'pass':'fail')} key={i}>{c.passed?<CheckCircle2 size={17}/>:<X size={17}/>}<div><strong>{c.name}</strong><span>{c.message}</span></div></div>)}</>:resultTab==='plan'?<pre>{output?.plan||'An execution plan is shown for Spark results.'}</pre>:<Result output={output}/>}</div></div></section>
    {tutorOpen&&<aside className="tutor-panel"><div className="tutor-heading"><Sparkles size={18}/><h3>Learning tutor</h3><button aria-label="Close tutor" className="icon-button" onClick={()=>setTutorOpen(false)}><X size={16}/></button></div><p className="muted">Ask about the concept or your approach. Feedback is provisional; execution checks verify behavior.</p>{tutorText&&<Md>{tutorText}</Md>}<label htmlFor="tutor-question">What are you working through?</label><textarea id="tutor-question" value={question} onChange={x=>setQuestion(x.target.value)} placeholder="Why does OPTIONAL drop this person?"/><button className="primary" disabled={!question.trim()||tutorBusy||mode==='assessment'} onClick={askTutor}>{tutorBusy?<Loader2 size={15} className="spin"/>:<Send size={15}/>}Ask tutor</button></aside>}
    </div>
  </section>
}

function Result({output}:{output:any}){if(!output)return <p className="muted">No public output yet.</p>;if(output.results){const vars=output.head.vars;return <div className="table-scroll"><table><thead><tr>{vars.map((v:string)=><th key={v}>?{v}</th>)}</tr></thead><tbody>{output.results.bindings.map((r:any,i:number)=><tr key={i}>{vars.map((v:string)=><td key={v}>{r[v]?.value??<em>unbound</em>}</td>)}</tr>)}</tbody></table></div>}if(output.rows){const vars=output.schema.fields.map((f:any)=>f.name);return <div className="table-scroll"><table><thead><tr>{vars.map((v:string)=><th key={v}>{v}</th>)}</tr></thead><tbody>{output.rows.map((r:any,i:number)=><tr key={i}>{vars.map((v:string)=><td key={v}>{String(r[v]??'null')}</td>)}</tr>)}</tbody></table></div>}return <pre>{JSON.stringify(output,null,2)}</pre>}

function Projects(){const [data,setData]=useState<any>(),[active,setActive]=useState<string>(),[error,setError]=useState('');useEffect(()=>{api('/projects').then(setData).catch(e=>setError(e.message))},[]);if(error)return <p className="error">{error}</p>;if(!data)return <Loader2 className="spin"/>;return <div className="projects-grid">{data.projects.map((p:any)=><section className="project-card" key={p.id}><span className="pill">CAPSTONE {p.number}</span><FolderGit2 size={28}/><h2>{p.title}</h2><p>{p.description}</p><div className="track-meta"><span>{p.milestones.length} milestones</span><span>{p.hours} hours</span></div><button className="outline" onClick={()=>setActive(active===p.id?undefined:p.id)}>{active===p.id?'Close project':'Open project'}<ArrowRight size={16}/></button>{active===p.id&&<div className="milestones"><Md>{p.brief}</Md><h3>Review rubric</h3><ul>{p.rubric.map((r:string)=><li key={r}>{r}</li>)}</ul>{p.milestones.map((m:any)=><MilestoneEditor key={m.id} project={p.id} milestone={m} saved={data.milestones.find((s:any)=>s.project_id===p.id&&s.milestone_id===m.id)}/>)}<Sources items={p.sources}/></div>}</section>)}</div>}
function MilestoneEditor({project,milestone:m,saved}:{project:string;milestone:any;saved:any}){const [notes,setNotes]=useState(saved?.notes||''),[completed,setCompleted]=useState(saved?.completed||false),[status,setStatus]=useState('');return <div className="milestone"><h3>{m.title}</h3><p>{m.description}</p><label>Implementation notes and evidence<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record your decisions, test evidence, and remaining questions."/></label><label className="answer-option"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)}/>Self-review complete</label><button className="outline" onClick={async()=>{try{await api(`/projects/${project}/milestones/${m.id}`,{method:'PUT',body:JSON.stringify({notes,completed})});setStatus('Saved')}catch(e){setStatus((e as Error).message)}}}>Save milestone</button><span className="muted">{status}</span></div>}
function Author(){const [data,setData]=useState<any>(),[error,setError]=useState('');useEffect(()=>{api('/author/validation').then(setData).catch(e=>setError(e.message))},[]);return <section className="reference-card"><h2>Exercise publication inventory</h2><p>Runtime validation and editorial review are recorded separately. Run the content verification command before a release.</p>{error&&<p className="error">{error}</p>}{data?.exercises.map((e:any)=><div className="outline-row" key={e.id}><strong>{e.id}</strong><span>{e.status}</span><span>{e.fixtures} fixtures · {e.wrong_solutions} counterexamples</span></div>)}</section>}
