"""Deterministic authoring compiler. Source lessons are reviewed independently of execution."""
from pathlib import Path
import json
import yaml
from rdflib import Graph

ROOT=Path(__file__).resolve().parents[1]/'content'
PREFIX='@prefix ex: <https://example.org/> .\n@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix owl: <http://www.w3.org/2002/07/owl#> .\n@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
QP='PREFIX ex: <https://example.org/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n'
SOURCES={
 'rdf':{'title':'W3C RDF 1.1 Primer','url':'https://www.w3.org/TR/rdf11-primer/'},
 'rdfs':{'title':'W3C RDF Schema 1.1','url':'https://www.w3.org/TR/rdf-schema/'},
 'sparql':{'title':'W3C SPARQL 1.1 Query','url':'https://www.w3.org/TR/sparql11-query/'},
 'update':{'title':'W3C SPARQL 1.1 Update','url':'https://www.w3.org/TR/sparql11-update/'},
 'owl':{'title':'W3C OWL 2 Primer','url':'https://www.w3.org/TR/owl2-primer/'},
 'shacl':{'title':'W3C SHACL','url':'https://www.w3.org/TR/shacl/'},
 'skos':{'title':'W3C SKOS Reference','url':'https://www.w3.org/TR/skos-reference/'},
 'prov':{'title':'W3C PROV-O','url':'https://www.w3.org/TR/prov-o/'},
 'jena':{'title':'Apache Jena TDB2','url':'https://jena.apache.org/documentation/tdb2/'},
 'txn':{'title':'Apache Jena Transactions','url':'https://jena.apache.org/documentation/txn/'},
 'arq':{'title':'Jena Query Explanation','url':'https://jena.apache.org/documentation/query/explain.html'},
 'spark':{'title':'PySpark DataFrame Guide','url':'https://spark.apache.org/docs/3.5.5/api/python/getting_started/quickstart_df.html'},
 'spark_sql':{'title':'Spark SQL Reference','url':'https://spark.apache.org/docs/3.5.5/sql-ref.html'},
 'spark_perf':{'title':'Spark Performance Tuning','url':'https://spark.apache.org/docs/3.5.5/sql-performance-tuning.html'},
}

# Each unit records an explanation, concrete example, misconception and transfer task.
MODULES=[
('o01','RDF foundations','Fundamentals',['rdf'],[
('Facts as triples','A triple describes one relationship: a subject resource, a predicate IRI, and an object resource or literal. A person is not the same thing as their name. Give the person an IRI so that employment, project, and contact facts can refer to the same resource. Splitting one statement into several triples allows new information without redesigning a row.','ex:ava ex:worksFor ex:northstar .\nex:ava ex:name "Ava" .','A string containing a company name does not link to the company resource.','Represent a person, their employer, and the employer name using three triples.'),
('IRIs, literals, and datatypes','IRIs identify resources; literals carry values. An integer, a date, and a language-tagged label are different RDF terms. A lexical form that looks numeric is not enough to select a numeric datatype. Preserve source precision and choose an explicit timezone policy for timestamps.','ex:ava ex:years "4"^^xsd:integer ;\n  ex:joined "2024-01-15"^^xsd:date ;\n  ex:name "Ava"@en .','Do not mix a language tag and a datatype annotation on the same literal.','Explain how "04"^^xsd:integer differs from the plain string "04".'),
('Blank nodes and reusable identity','A blank node says that a resource exists without assigning it a global IRI. It is useful for a local address or restriction expression. Its serialization label is not a persistent external identifier. A resource that must be joined across snapshots usually needs a stable IRI.','ex:ava ex:address [ ex:city "Porto" ; ex:country "PT" ] .','Two blank nodes with similar fields are not automatically the same resource.','Decide whether an employee assignment that changes weekly needs a stable IRI.'),
('Turtle and RDF datasets','Turtle abbreviates triples using prefixes, semicolons, and commas. A semicolon keeps the subject; a comma keeps both subject and predicate. Named graphs belong to an RDF dataset, not to an individual triple. Use TriG or N-Quads when serializing named graphs.','ex:ava a ex:Person ;\n  ex:name "Ava" ;\n  ex:skill ex:SPARQL, ex:Python .','The order of triples in a Turtle file does not define a query result order.','Expand the example into four complete triples and explain each term.')]),
('o02','RDFS and vocabulary design','Fundamentals',['rdfs','rdf'],[
('Classes and instances','A class groups resources. Typing Ava as an Engineer states membership; subclassing Engineer under Person states that every Engineer is a Person. The class resource and its members play different roles. Choose names that make this distinction clear.','ex:Engineer rdfs:subClassOf ex:Person .\nex:ava a ex:Engineer .','A subclass statement is not an assertion that the class itself is a person.','Predict the type inferred for Ava and identify the two statements supporting it.'),
('Domain and range infer types','RDFS domain and range are inference rules. If worksFor has domain Person and range Company, using the property entails those endpoint types. These declarations do not reject an unexpected endpoint the way a database constraint would.','ex:worksFor rdfs:domain ex:Person ; rdfs:range ex:Company .\nex:ava ex:worksFor ex:northstar .','Multiple domains imply membership in all of them, not a choice between them.','Show why assigning a Project as the subject also leads to a Person inference.'),
('Property hierarchies','A subproperty lets a specialized relationship imply a general one. Every managesProject link may count as contributesTo, while a contribution does not necessarily imply management. Keep the implication directional.','ex:managesProject rdfs:subPropertyOf ex:contributesTo .\nex:ava ex:managesProject ex:atlas .','Subproperty relationships do not automatically define inverse relationships.','Write a query that benefits from general contributions when inference is enabled.'),
('Names, labels, and documentation','An IRI is an identifier, while rdfs:label provides a human-facing name. Labels can change or be translated without replacing the resource. Document intended usage, examples, and any assumptions about lifecycle.','ex:Person rdfs:label "Person"@en, "Pessoa"@pt ;\n  rdfs:comment "A human represented in the workforce graph." .','Matching labels do not establish identity between classes or individuals.','Design a stable IRI and two labels for a department whose name changes.')]),
('o03','SPARQL fundamentals','Fundamentals',['sparql'],[
('Write a complete graph pattern','A basic graph pattern joins triple patterns through shared variables. Start from the relationship needed by the question, then add patterns that connect it to names or categories. Every selected variable should have an intentional binding source.','SELECT ?person ?company WHERE {\n  ?person a ex:Person ; ex:worksFor ?company .\n}','Variables with different names do not join just because their values seem related.','Write a complete query from an empty editor for employees of Northstar.'),
('Join through an association','An Assignment can connect a Person and Project while carrying its own role and allocation. Follow the association resource rather than inventing a direct edge that is absent from the data. Count what the question asks: people, assignments, or projects.','SELECT ?person ?project WHERE {\n  ?a ex:person ?person ; ex:project ?project .\n  ?project ex:client ex:acme .\n}','Two assignments for one person can legitimately create two result rows.','Explain which variable identifies the association and why it matters.'),
('Filter values deliberately','FILTER keeps solution mappings for which an expression evaluates true. Numeric comparisons depend on compatible datatypes. A filter using an unbound variable generally produces an error for that mapping, which does not pass the filter.','SELECT ?person WHERE {\n  ?person ex:years ?years .\n  FILTER(?years >= 3)\n}','The textual position of FILTER inside the same group is not a promise of earlier physical execution.','Query people with at least three years of experience and explain a missing years value.'),
('Bind expressions and constrain inputs','BIND names an expression result. VALUES supplies explicit bindings and is useful for a small set of allowed identifiers. Keep computed labels separate from resource identity, and use parameterization rather than unsafe user-input concatenation.','SELECT ?person ?nextYear WHERE {\n  VALUES ?person { ex:ava ex:ben }\n  ?person ex:years ?years .\n  BIND(?years + 1 AS ?nextYear)\n}','A computed display string should not silently replace the original resource IRI.','Extend the query with another allowed person and predict which rows survive.')]),
('o04','SPARQL composition','Fundamentals',['sparql'],[
('Optional data without losing people','OPTIONAL extends existing mappings when a match exists and preserves them when no match exists. Put the required person pattern outside the optional group. Inspect unbound values explicitly rather than interpreting them as empty strings.','SELECT ?person ?email WHERE {\n  ?person a ex:Person .\n  OPTIONAL { ?person ex:email ?email }\n}','A FILTER on email outside OPTIONAL can remove people with no email.','Retain every person while selecting only work-domain email values inside OPTIONAL.'),
('Union expresses alternatives','UNION evaluates alternative graph patterns and combines their solution mappings. Use the same variable names for compatible output columns. A record satisfying both alternatives can occur twice; deduplication is a separate choice.','SELECT ?person WHERE {\n  { ?person ex:worksFor ex:northstar }\n  UNION\n  { ?person ex:contractsFor ex:northstar }\n}','UNION does not mean both branches must match, and does not automatically remove duplicates.','Create a fixture where one person matches both branches and count the rows.'),
('Absence and correlated existence','FILTER NOT EXISTS tests whether a pattern has a match under current bindings. MINUS removes compatible mappings with shared variables and has different behavior when no variables are shared. Choose deliberately rather than assuming these forms are interchangeable.','SELECT ?person WHERE {\n  ?person a ex:Person .\n  FILTER NOT EXISTS { ?person ex:email ?email }\n}','Absence in the queried graph is not proof that the fact is false in the world.','Describe the dataset scope in which the returned people have no recorded email.'),
('Duplicates are part of the result','SPARQL SELECT produces a multiset of solution mappings. Joins can multiply rows; DISTINCT removes duplicates across the projected variables. First inspect why duplicates exist, then decide whether removing them matches the question.','SELECT DISTINCT ?person WHERE {\n  ?assignment ex:person ?person ; ex:project ?project .\n}','Adding DISTINCT can hide a modeling or join mistake without repairing it.','Compare counts of assignments and unique people using the same graph.')]),
('o05','Advanced SPARQL','Intermediate',['sparql','update'],[
('Aggregation and subqueries','GROUP BY groups mappings before aggregates are computed. COUNT(*) counts rows; COUNT(?x) ignores unbound values; COUNT(DISTINCT ?x) counts distinct bound values. A subquery can establish a grouping level before later joins multiply results.','SELECT ?company (COUNT(DISTINCT ?person) AS ?people) WHERE {\n ?person ex:worksFor ?company\n} GROUP BY ?company','A label join after grouping can still multiply output when labels have multiple languages.','Count employees per company, then explain the grouping key.'),
('Paths and reachability','Property paths traverse relationships. A plus means one or more steps; a star also includes zero steps. Sequence joins steps, alternatives choose predicates, and inverse paths traverse in the opposite direction. Think about cycles and endpoint bindings before using broad paths.','SELECT ?manager WHERE { ex:ava ex:reportsTo+ ?manager }','A zero-length path can return the starting node, even without an outgoing edge.','Compare the outputs of reportsTo+ and reportsTo* on a three-person chain.'),
('Named graphs and graph construction','GRAPH chooses a named graph in a dataset. The default graph is not universally the union of named graphs. CONSTRUCT creates an RDF graph, so duplicate identical triples collapse even when underlying solution mappings repeat.','CONSTRUCT { ?p ex:employer ?c } WHERE {\n GRAPH ex:snapshot { ?p ex:worksFor ?c }\n}','A named graph IRI does not by itself define who asserted its content or when.','Build a normalized employer graph from one explicitly selected snapshot.'),
('Updates and dataset state','INSERT DATA adds explicit triples; DELETE/INSERT WHERE transforms matches. Design updates so retries produce the intended state. A sequence of HTTP requests is not automatically a transaction across all requests.','DELETE { ?p ex:oldName ?name }\nINSERT { ?p ex:name ?name }\nWHERE { ?p ex:oldName ?name }','Generating new blank nodes on every retry can make a transformation non-idempotent.','Show why running this migration twice does not create a second name assertion.')]),
('o06','Modeling method','Intermediate',['rdf','owl','skos'],[
('Start with competency questions','Competency questions define what a graph must answer. Turn a business request into concrete questions about entities, time, and granularity before choosing classes. A model can be elegant yet fail the questions it was built to support.','SELECT ?person ?role WHERE {\n ?a ex:person ?person ; ex:project ex:atlas ; ex:role ?role\n}','Drawing class boxes before deciding required questions often misses relationship attributes.','Write three workforce questions and identify the facts each one requires.'),
('Identity and lifecycle','Make something a first-class resource when it must be identified, linked, reused, tracked through changes, or given its own evidence. Not every noun needs a class. A scalar measurement usually remains a literal unless it needs qualifiers or independent identity.','ex:order42 a ex:Order ; ex:status "shipped" .\nex:line42a a ex:OrderLine ; ex:order ex:order42 ; ex:quantity 2 .','A mutable label is usually a poor basis for a persistent entity identifier.','Decide which identifiers survive a product rename or an order correction.'),
('Associations with attributes','Use an association resource when a relationship has attributes such as dates, role, price, or allocation. OrderLine separates a particular purchase of a product from the product itself. Assignment separates a person-project relationship from either endpoint.','ex:a1 a ex:Assignment ; ex:person ex:ava ;\n ex:project ex:atlas ; ex:allocation "0.5"^^xsd:decimal .','Putting allocation directly on Person loses which project the allocation belongs to.','Represent two simultaneous assignments with different roles and allocations.'),
('Taxonomy versus entity model','A category can be a reusable concept in a controlled vocabulary. A Brand may need its own identity because products link to it and its owner can change. SKOS broader relationships and OWL subclass statements express different meanings.','@prefix skos: <http://www.w3.org/2004/02/skos/core#> .\nex:Tools a skos:Concept ; skos:prefLabel "Tools"@en .','A broader category does not automatically mean every instance is an OWL subclass instance.','Explain whether Brand, Category, and OrderLine need independent identity in your application.')]),
('o07','OWL foundations','Intermediate',['owl'],[
('Necessary and sufficient conditions','Subclassing states a necessary condition: membership in a subclass entails membership in its superclass. Equivalent classes state both directions. Defining Employee as equivalent to Person and an employment restriction can classify people whose facts satisfy the definition.','ex:Employee rdfs:subClassOf ex:Person .','The reverse inference from Person to Employee is not licensed by this axiom.','Give one individual that can be a Person without being inferred to be an Employee.'),
('Open-world reasoning','OWL reasons about what follows from asserted axioms, allowing additional unrecorded facts. Failure to prove a statement is different from proving its negation. This distinction matters when incomplete source data is used for inference.','ex:ava a ex:Person .\n# No employer is recorded here.','A missing worksFor triple does not entail that Ava has no employer.','Separate a data-completeness rule from a logical statement about employment.'),
('Disjointness and consistency','Disjoint classes cannot share an individual in a consistent ontology. An unsatisfiable class cannot have any instances, but an ontology containing that empty class can still be consistent. Asserting an instance of it creates inconsistency.','ex:Person owl:disjointWith ex:Company .\nex:ava a ex:Person .','An empty class in the current data is not necessarily an unsatisfiable class.','Explain what changes if Ava is also asserted to be a Company.'),
('Properties have logical characteristics','An inverse property reverses a relationship; a transitive property carries a relationship across a chain; symmetry entails the reverse edge. Functionality restricts values semantically and may imply equality rather than simply rejecting multiple named values.','ex:employs owl:inverseOf ex:worksFor .','Declaring worksFor symmetric would imply that a company works for its employees.','Choose inverse, symmetric, or transitive behavior for three example predicates and justify each.')]),
('o08','OWL restrictions and reasoning','Intermediate',['owl'],[
('Existential and universal restrictions','An existential restriction requires some qualifying value in every model, but the value need not have an explicit name or triple in the input. A universal restriction constrains any values that exist and does not require at least one.','ex:Employee rdfs:subClassOf [ a owl:Restriction ;\n owl:onProperty ex:worksFor ; owl:someValuesFrom ex:Company ] .','Universal restrictions can hold when there are no values at all.','Explain why an Employee with no recorded employer can remain consistent.'),
('Cardinality and identity','Qualified cardinality counts values belonging to a specified class. OWL does not assume different names identify different individuals. With a maximum of one employer, two employer names may be inferred equal unless their difference or other facts causes a contradiction.','ex:SingleEmployerPerson rdfs:subClassOf [ a owl:Restriction ;\n owl:onProperty ex:worksFor ; owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ; owl:onClass ex:Company ] .','Two distinct IRI strings are not sufficient to prove two distinct individuals in OWL.','Add explicit difference and predict how the reasoning result can change.'),
('Diagnose unsatisfiable classes','A class that inherits from two disjoint classes cannot have members. To debug, isolate the smallest conflicting set of axioms. Separate ontology consistency, class satisfiability, and expected classification into distinct tests.','ex:Impossible rdfs:subClassOf ex:Person, ex:Company .\nex:Person owl:disjointWith ex:Company .','A reasoner timeout does not demonstrate consistency or inconsistency.','Remove one conflicting axiom and state the meaning you lose.'),
('Profiles and reasoning contracts','OWL profiles restrict language features to support different computational tradeoffs. Record the supported profile and the reasoner version with an exercise. A rule-based subset cannot silently stand in for arbitrary OWL 2 DL reasoning.','ex:Person a owl:Class .\nex:worksFor a owl:ObjectProperty .','A successful Turtle parse does not prove that an ontology satisfies OWL 2 DL global restrictions.','Define separate checks for parsing, profile validity, consistency, and intended entailments.')]),
('o09','SHACL foundations','Validation',['shacl'],[
('Targets and focus nodes','A NodeShape defines constraints for selected focus nodes. sh:targetClass selects class instances under SHACL target semantics, including the relevant subclass paths. A shape that targets no data may report conformance without testing the entities you intended.','ex:PersonShape a sh:NodeShape ; sh:targetClass ex:Person .','A conforming report can mean that no focus nodes were selected.','Add a Person instance and demonstrate that your target actually selects it.'),
('Paths and cardinality','A property shape follows sh:path from each focus node, then applies minCount and maxCount to its value nodes. Exactly one requires both constraints. RDF graphs collapse duplicate identical triples before cardinality is checked.','ex:PersonShape sh:property [ sh:path ex:employeeId ;\n sh:minCount 1 ; sh:maxCount 1 ] .','maxCount 1 alone permits zero values.','Build fixtures with zero, one, and two different employee identifiers.'),
('Class and datatype constraints','Use sh:class when values should be resources of a class and sh:datatype when they should be typed literals. These are different contracts. Decide whether validation sees explicit facts or a separately materialized inference graph.','ex:PersonShape sh:property [ sh:path ex:worksFor ; sh:class ex:Company ] ;\n sh:property [ sh:path ex:employeeId ; sh:datatype xsd:string ] .','An IRI whose text resembles a company name does not establish its class.','Show one invalid literal employer and one valid Company resource.'),
('Read validation reports','A validation result identifies a focus node, a constraint component, and often a path and offending value. Use these fields to explain failures without relying on engine-specific English messages. Distinguish a malformed shapes graph from invalid data.','ex:PersonShape sh:property [ sh:path ex:employeeId ;\n sh:minCount 1 ; sh:message "Provide an employee identifier." ] .','Changing a validation message does not repair a failing constraint.','For a missing employeeId, identify the focus node, path, and cardinality rule.')]),
('o10','Advanced SHACL','Validation',['shacl'],[
('Nested shapes and paths','sh:node validates a value node against another shape. A sequence path follows multiple predicates, while an inverse path follows edges backward. Choose whether a nested resource is optional separately from whether an existing one must conform.','ex:PersonShape sh:property [ sh:path ex:address ;\n sh:node ex:AddressShape ] .','A nested shape does not require the property to exist without minCount.','Require an address only for the subset of people defined by the stated policy.'),
('Logical combinations','sh:or requires at least one alternative; sh:and requires every alternative; sh:xone requires exactly one. Build a truth table before coding a conditional business rule. A record satisfying two alternatives fails xone but passes or.','ex:ContactShape sh:or (\n [ sh:property [ sh:path ex:email ; sh:minCount 1 ] ]\n [ sh:property [ sh:path ex:phone ; sh:minCount 1 ] ]\n) .','Using xone for email-or-phone rejects people who provide both.','Test neither contact, email only, phone only, and both.'),
('Closed shapes and extension','A closed shape limits allowed outgoing properties, subject to explicitly ignored predicates. Use it where a narrow contract is intentional. Closing a general-purpose entity shape can make harmless vocabulary extensions fail validation.','ex:PersonShape sh:closed true ; sh:ignoredProperties ( rdf:type ) .','Closed shapes do not automatically forbid every incoming relationship.','Allow rdf:type and employeeId while rejecting an accidental misspelled property.'),
('SPARQL constraints and scope','A SHACL SPARQL constraint reports violating solutions, typically involving $this. Keep the intended data graph and validation scope clear. Prefer Core constraints when they express the requirement directly, and reserve custom queries for rules such as cross-field comparisons.','SELECT $this WHERE {\n $this ex:start ?start ; ex:end ?end .\n FILTER(?end < ?start)\n}','A query returning valid nodes instead of violating nodes reverses the rule.','Validate that an assignment end date is not before its start date.')]),
('o11','Reuse and ontology lifecycle','Integration',['skos','owl'],[
('Choose what to reuse','Evaluate a vocabulary by semantic fit, identifier stability, governance, documentation, and maintenance. Reusing a familiar term with the wrong meaning creates integration debt. Record why a local term is needed when no suitable existing term exists.','@prefix skos: <http://www.w3.org/2004/02/skos/core#> .\nex:Tools a skos:Concept .','Popularity does not make a vocabulary term semantically appropriate.','Compare two candidate terms against your competency questions and record the tradeoff.'),
('Concept schemes and labels','SKOS separates concepts, labels, concept schemes, and semantic relationships. A concept can have multilingual labels while retaining identity. Prefer a concept scheme for managed categories when logical class restrictions are not required.','@prefix skos: <http://www.w3.org/2004/02/skos/core#> .\nex:Tools skos:inScheme ex:Catalog ; skos:prefLabel "Tools"@en .','Category labels alone are not a stable cross-system identifier.','Represent a concept in two languages and link it to the catalog scheme.'),
('Mappings have different strength','An OWL equivalence statement is a logical commitment, not a fuzzy match score. SKOS mapping predicates carry their own semantics. Preserve weaker mappings where source concepts differ, and keep evidence alongside the mapping decision.','@prefix skos: <http://www.w3.org/2004/02/skos/core#> .\nex:SourceTools skos:closeMatch ex:Tools .','A close textual match does not justify equivalentClass or sameAs.','Explain what evidence would be required before strengthening a mapping.'),
('Version and deprecate deliberately','Keep ontology identity separate from version identity. Document deprecated terms and their replacements. A change to a restriction can alter inference without changing a single data triple, so run entailment and validation regression tests.','ex:LegacyEmployee owl:deprecated true ; rdfs:comment "Use Employee for new data." .','Deleting a term without migration can break old queries and source mappings.','Write a migration note for renaming a property while preserving old consumers.')]),
('o12','Semantic integration and entity resolution','Integration',['prov','owl'],[
('Normalize without erasing evidence','Normalize fields for comparison but preserve the original source values. Whitespace, casing policies, dates, and missing-value markers need explicit rules. Email local-part normalization needs a chosen policy; blindly rewriting all addresses can create false matches.','ex:record1 ex:rawEmail " Ava@Example.org " ; ex:comparisonEmail "Ava@example.org" .','A comparison value is not necessarily a replacement for the source field.','Describe which transformations are reversible and which need source retention.'),
('Deterministic matching','A deterministic rule matches records using explicit conditions. A strong identifier still needs scope and lifecycle: an employee number may be unique only within a company. Detect conflicting evidence before accepting a merge.','ex:match1 ex:left ex:sourceA ; ex:right ex:sourceB ; ex:rule "company+employeeId" .','Matching email alone can merge shared mailboxes or reassigned accounts.','Build a conflict case with the same email but incompatible employee identifiers.'),
('Confidence and review','Separate candidate generation, scoring, and decision thresholds. A score is meaningful only with calibration and a defined population. Use accept, reject, and review bands, and evaluate false merges as well as missed matches.','ex:match1 ex:score "0.82"^^xsd:decimal ; ex:decision "review" .','A decimal score is not automatically a probability that the identity is correct.','Explain the consequences of raising an auto-accept threshold on precision and recall.'),
('Identity assertions and provenance','Preserve source records even when a canonical entity is created. Record the mapping activity, evidence, rule version, and reviewer decision. Strong identity assertions can propagate many other facts through reasoning, so make them governed outputs.','@prefix prov: <http://www.w3.org/ns/prov#> .\nex:canonicalAva prov:wasDerivedFrom ex:recordA, ex:recordB .','Replacing source records with sameAs edges can discard the evidence needed to undo a bad match.','Design a reversible merge record and explain how an incorrect match would be repaired.')]),
('o13','Ingestion and publication','Production',['update','prov','txn'],[
('Snapshots and mapping versions','Treat a source snapshot and mapping version as inputs to a reproducible transformation. Use stable identifiers based on appropriate source keys. A reproducible output also requires fixed normalization and datatype policies.','ex:load42 ex:snapshot "2026-09-01" ; ex:mappingVersion "2.1" .','A current source URL does not identify the exact bytes used by a historical load.','Specify enough metadata to rebuild the same graph six months later.'),
('Stage and validate','Load into a staging graph, validate its completeness and constraints, then publish only acceptable data. Quarantine invalid records with reasons and source references. Count inputs, accepted records, and rejected records to reconcile the load.','INSERT { GRAPH ex:staging { ?s ?p ?o } }\nWHERE { ?s ?p ?o }','Silently dropping invalid records can make the resulting graph look valid but incomplete.','Explain how to distinguish a clean load from an empty load.'),
('Idempotent transformations','A retry should not create a second representation of the same business fact. Stable IRIs and replacement of a well-defined snapshot graph can make retries predictable. Blank nodes generated afresh on each attempt need special care.','INSERT { GRAPH ex:staging { ?person ex:normalizedName ?name } }\nWHERE { ?person ex:rawName ?name }','Appending fresh anonymous association nodes on every retry breaks idempotency.','Run the update twice and compare the resulting graph, not just the success response.'),
('Publish atomically','Within one transactional dataset, readers should see either the old published graph or the complete new graph. Keep validation and promotion boundaries explicit. Atomicity across unrelated services requires a broader design and is not supplied by SPARQL syntax alone.','CLEAR GRAPH ex:published ;\nADD GRAPH ex:staging TO GRAPH ex:published','Two independently committed requests can expose an intermediate empty graph.','Place promotion in one transaction and predict what a concurrent reader observes.')]),
('o14','Triplestore operations','Production',['jena','txn'],[
('Bulk loading and serving','Bulk loaders optimize ingestion under documented operating conditions. Some require exclusive dataset access. Choose a loader based on the storage engine, graph size, and availability requirements, and verify the resulting dataset before serving queries.','SELECT (COUNT(*) AS ?triples) WHERE { ?s ?p ?o }','A successful loader exit does not establish semantic completeness or validate constraints.','List the checks needed before making a newly loaded dataset available.'),
('Transactions and concurrent readers','A transaction defines a consistency boundary for a sequence of operations. Readers and writers follow the engine isolation model. Never have unrelated processes manipulate the same embedded storage files without the documented access protocol.','DELETE { ex:state ex:version ?old }\nINSERT { ex:state ex:version "2" }\nWHERE { ex:state ex:version ?old }','File-level sharing of an embedded dataset is not a substitute for a supported server endpoint.','Explain how a reader should behave while a writer replaces a snapshot.'),
('Retries and ambiguous outcomes','A timeout can occur after a server commits but before the client receives confirmation. An idempotency key and a persisted operation record let the client discover the outcome. Retry transient failures with bounds and backoff; surface invalid input immediately.','ex:operation42 ex:status "committed" ; ex:targetSnapshot ex:snapshot42 .','Retrying every exception can duplicate non-idempotent operations and hide deterministic failures.','Describe how to recover when the response is lost after commit.'),
('Backup and restore evidence','A recovery procedure is tested by restoring and checking data, not by producing a backup file. Record what is backed up, its consistency point, retention, encryption, and restore dependencies. Re-run count and competency checks after restoration.','ASK { ex:operation42 ex:status "committed" }','An untested backup does not demonstrate a working recovery process.','Define acceptance checks for a restored graph and compare them with the original snapshot.')]),
('o15','Query performance','Production',['sparql','arq'],[
('Selectivity and cardinality','Selective patterns reduce candidate mappings. Join cardinality determines how much intermediate work is produced. Inspect the data distribution and execution plan rather than assuming the order written in the query is the physical order executed.','SELECT ?person WHERE {\n ?person ex:employeeId "E-001" ; ex:worksFor ?company\n}','Placing a selective pattern first in text does not force an optimizer to execute it first.','Estimate intermediate rows for joining employees to every label in the graph.'),
('Avoid accidental Cartesian products','Patterns without shared variables combine independently, multiplying solutions. Sometimes that is intentional, but usually a missing join variable is the cause. DISTINCT may reduce final output while leaving the expensive intermediate computation intact.','SELECT ?person ?company WHERE {\n ?person ex:worksFor ?company .\n ?company ex:name ?name .\n}','Using ?employer in one pattern and ?company in the next can leave the intended join disconnected.','Construct a tiny fixture where a missing join produces six rows instead of two.'),
('Scope optional and path work','Bind endpoints and choose graph scope before exploring expensive paths when semantics allow. Broad optional branches and unconstrained reachability can produce much larger intermediate results. Preserve the original meaning while testing alternatives.','SELECT ?manager WHERE {\n GRAPH ex:current { ex:ava ex:reportsTo+ ?manager }\n}','Moving a filter across OPTIONAL may change which incomplete records are retained.','Compare two equivalent queries using result equality before comparing performance.'),
('Measure a controlled experiment','Record engine version, dataset, statistics, cache state, query plan, and repeated timings. Warm and cold runs answer different questions. For shared hardware, timing noise should not decide whether a logically correct solution passes.','SELECT (COUNT(DISTINCT ?person) AS ?n) WHERE { ?person ex:worksFor ?c }','A single fast run is not evidence that a change reliably improves performance.','Prepare a before/after report with identical outputs and an explanation of changed work.')]),
('o16','Governance and release','Production',['prov','owl','shacl'],[
('Compatibility is behavioral','An ontology release can change query results, inferred types, or validation outcomes. Define compatibility in terms of consumer behavior. Test stored competency queries and constraints against representative old and new data.','ex:release2 ex:replaces ex:release1 ; ex:changeType "additive" .','Adding an axiom is not always backward-compatible for reasoning or validation consumers.','Explain how a new disjointness axiom can break previously consistent data.'),
('Migration and provenance','A migration transforms data under a named mapping version. Retain provenance and a rollback strategy. If a transformation loses information, rollback may require the source snapshot rather than a simple inverse query.','@prefix prov: <http://www.w3.org/ns/prov#> .\nex:snapshot2 prov:wasDerivedFrom ex:snapshot1 .','Not every transformation can be inverted from its output alone.','Describe the evidence needed to reverse an erroneous entity merge.'),
('Observe meaning and operations','Monitor ingestion volumes, quarantine reasons, missing required relationships, consistency, and query errors alongside CPU and memory. An operationally healthy service can still publish the wrong meaning. Define thresholds with expected data changes in mind.','SELECT (COUNT(?p) AS ?missing) WHERE {\n ?p a ex:Person . FILTER NOT EXISTS { ?p ex:employeeId ?id }\n}','A sudden drop in validation violations might result from an empty target graph.','Pair each semantic metric with a coverage or volume metric.'),
('Release with explicit ownership','Record who owns vocabulary changes, mapping decisions, review queues, and recovery. Separate read access from publication authority. A release checklist should connect requirements to executable evidence and identify any manual judgment still needed.','ex:release2 ex:approvedBy ex:reviewer ; ex:validationReport ex:report42 .','Passing automated checks does not certify that every open-ended modeling decision is appropriate.','Write a release record linking source versions, tests, approvals, and rollback instructions.')]),
('o17','Query optimization and benchmarking','Production',['sparql','arq','jena'],[
('Measure before tuning','Treat performance as an experiment. Record dataset size, inference mode, graph scope, engine version, cache state, query plan, cardinality, latency, and resource use. Preserve result semantics before comparing measurements.','SELECT ?person WHERE { ?person ex:employeeId "E-001" ; ex:worksFor ?company }','A faster query that removes required optional rows or duplicates is not an equivalent optimization.','Create a benchmark note that makes two query runs comparable.'),
('Use selective constraints','Exact identifiers, narrow graph scope, and constrained values can reduce intermediate bindings. The engine may reorder basic graph patterns, so textual order is not a physical-plan guarantee.','SELECT ?person ?company WHERE { ?person ex:employeeId "E-001" ; ex:worksFor ?company }','Moving a FILTER across OPTIONAL can change results even when it seems like a performance improvement.','Identify a selective pattern and a pattern that can multiply rows.'),
('Control joins and cardinality','Shared variables connect patterns. Missing joins make Cartesian products; DISTINCT can hide output duplication while retaining expensive work. Estimate intermediate cardinalities and aggregate at the intended grain.','SELECT ?person ?companyName WHERE { ?person ex:worksFor ?company . ?company ex:name ?companyName }','A label join after grouping can change the count when an entity has multiple labels.','Repair a disconnected join and explain its output grain.'),
('Bound paths and optionals','Unbounded paths and broad OPTIONAL branches can expand on cyclic or high-degree graphs. Bind endpoints, scope graphs, inspect plans, and preserve semantics while testing alternatives.','SELECT ?person WHERE { ?person ex:reportsTo+ ex:cyra }','A property path is not automatically an indexed recursive lookup.','Define a safe reporting-chain query and its operational limit.')]),
('o18','Dataset architecture, federation, and search','Production',['sparql','jena','prov'],[
('Design named-graph boundaries','Named graphs separate source snapshots, staging, quarantine, publication, and provenance. They do not by themselves provide access control, transactions, or truth claims.','SELECT ?person WHERE { GRAPH ex:snapshot { ?person ex:worksFor ex:northstar } }','The default graph is not universally the union of every named graph.','Choose graph names and purposes for a publication pipeline.'),
('Federate deliberately','Federated queries depend on remote services. Specify ownership, credentials, result limits, timeouts, retries, and fallback snapshots before adding a SERVICE dependency.','SELECT ?person WHERE { GRAPH ex:snapshot { ?person a ex:Person } }','Federation does not make remote availability or statistics predictable.','Decide when to query a remote source live and when to ingest a snapshot.'),
('Pair search with graph evidence','A search index supports lexical discovery while the graph answers identity, provenance, and relationship questions. Version an index from published graph data and expose the indexed graph release.','SELECT ?resource ?label WHERE { ?resource rdfs:label ?label }','A text-search hit is not an RDF entailment or identity assertion.','Design the link from a search hit to its resource and publication version.'),
('Cache with provenance','Cache entries need dataset version, parameters, graph scope, and inference mode. Invalidate or version them when publication changes.','SELECT ?company (COUNT(DISTINCT ?person) AS ?people) WHERE { ?person ex:worksFor ?company } GROUP BY ?company','A cached answer without a graph version cannot be audited after a correction.','Write cache metadata for a high-traffic query.')]),
('o19','Reliable ingestion, storage, and recovery','Production',['jena','txn','shacl','prov'],[
('Bulk load and validate in stages','Bulk loading optimizes placement but does not remove source contracts, mapping versions, validation, quarantine, and atomic promotion. Measure loading and index build separately.','INSERT { GRAPH ex:staging { ?s ex:name ?name } } WHERE { ?s ex:rawName ?name }','A successful parse does not establish that data satisfies a published graph contract.','List the evidence retained for a bulk-load run.'),
('Retry unknown outcomes safely','A timeout can happen after commit. Use stable identifiers, operation records, and bounded retry to discover the outcome rather than assuming the transaction failed.','INSERT { GRAPH ex:published { ?s ex:employeeId ?id } } WHERE { ?s a ex:Person ; ex:employeeId ?id }','A generated identifier per retry can create duplicate business entities.','Describe an idempotency key and unknown-outcome procedure.'),
('Restore and reconcile','Test a backup by restoring it and running counts, validation, and competency queries against recorded source and mapping versions.','SELECT (COUNT(?person) AS ?people) WHERE { GRAPH ex:published { ?person a ex:Person } }','Restoring database bytes alone does not prove the restored graph is the intended release.','Create a restore checklist with a reconciliation query.'),
('Isolate concurrent workloads','Document transaction behavior, back-pressure, worker limits, and workload separation. Keep bulk loads and expensive analytics from starving time-sensitive publication operations.','SELECT ?person ?email WHERE { ?person a ex:Person OPTIONAL { ?person ex:email ?email } }','Unbounded retries under overload can amplify queue pressure.','Choose metrics and limits for load and interactive-query queues.')]),
('o20','Production governance, security, and incident response','Production',['prov','shacl','owl','jena'],[
('Define access boundaries','Use least-privilege read, write, publication, operations, and administration roles. Named-graph boundaries alone are not an authorization model.','SELECT ?person WHERE { GRAPH ex:published { ?person a ex:Person } }','Hiding a graph name in a client is not access control.','Map each operational role to the minimum actions and data it needs.'),
('Protect sensitive graph data','Classify sensitive predicates, minimize retention, encrypt backups and transport, and preserve access evidence without writing sensitive values to logs.','SELECT ?person ?email WHERE { ?person ex:email ?email }','An apparently anonymous graph can become identifiable when joined with other facts.','Write a handling contract for employee contact data.'),
('Respond to incidents','Preserve bounded evidence, stop unsafe promotion, identify affected graph versions, revoke access when needed, restore a known-good release, and rehearse this procedure.','SELECT ?release ?snapshot WHERE { ?release ex:rollbackTarget ?snapshot }','Deleting logs or graph data immediately can destroy the evidence needed for recovery.','Draft an incident timeline for a bad mapping release.'),
('Govern change and deprecation','Review compatibility, mapping impacts, validation, query behavior, access effects, and rollback. Deprecate terms with migration guidance and retain historical versions when required.','SELECT ?term WHERE { ?term owl:deprecated true }','Changing an IRI meaning without migration can silently break historical queries.','Plan a compatible replacement for a deprecated predicate.')]),
('s01','Spark execution model','Fundamentals',['spark','spark_perf'],[
('Driver, executors, and a DataFrame','The driver builds the computation and coordinates tasks. Executors perform work on partitions. A DataFrame represents a distributed table with a schema and a plan, not a local Python list. The initial labs use local mode while retaining Spark planning behavior.','result = people.select("name", "years")','Calling collect moves rows to driver memory; it does not make a large dataset inexpensive.','Explain where the plan is built and where row processing occurs.'),
('Lazy transformations and actions','Transformations build a plan. An action asks Spark to produce a result and triggers execution. A chain of selects and filters does not necessarily create separate full scans because the optimizer can combine work.','result = people.filter("years >= 3").select("name")\n# The grading harness triggers an action.','A transformation line is not necessarily a Spark job boundary.','Predict when an invalid expression is analyzed and when data must be read.'),
('Partitions and parallel work','Partitions are units of data processing, and tasks operate on them. Increasing partition count can increase parallelism but also scheduling overhead. A tiny exercise dataset cannot prove how a large distributed workload will scale.','result = people.repartition(2).select("name")','More partitions do not guarantee faster execution for every dataset.','Explain why repartitioning can introduce a shuffle and why it may be unnecessary here.'),
('Inspect the plan','A logical plan describes requested transformations; the physical plan describes selected execution operations. Inspect scans, projections, exchanges, and joins. Use the plan to form hypotheses, then measure on a suitable dataset.','result = people.select("name")\nresult.explain(True)','The plan text may change across Spark versions without changing the answer.','Find a projection in the plan and connect it to the selected columns.')]),
('s02','DataFrames and schemas','Fundamentals',['spark','spark_sql'],[
('Schema is a contract','A schema defines field names, types, and nullability. Explicit schemas make exercises and pipelines repeatable. Schema inference can change behavior when input samples change, especially for empty datasets or mixed values.','result = people.select("name", "years")\nprint(result.schema)','A column containing numeric-looking strings is not necessarily an integer column.','Specify the expected output schema before writing the transformation.'),
('Select and rename columns','Projection controls output columns and their names. Use aliases to produce the stated contract and avoid duplicate ambiguous names after joins. Selecting the right values with the wrong schema can break a downstream consumer.','from pyspark.sql import functions as F\nresult = people.select(F.col("name").alias("person_name"))','Column position and naming should not be left accidental in a published table.','Produce one renamed column and verify both the name and its values.'),
('Data types and explicit casts','Casting changes a column type under Spark SQL rules. Decide how malformed values should be handled and pin relevant SQL settings. A cast that yields null needs a quarantine or validation policy when the field is required.','from pyspark.sql import functions as F\nresult = people.select(F.col("years").cast("long").alias("years"))','Casting is not a substitute for deciding what invalid source values mean.','Describe a test for malformed input and a test for an actual missing value.'),
('Empty data still has structure','An empty DataFrame retains its schema. Pipelines should produce valid empty outputs rather than failing because no sample row exists. Test schema preservation independently from row equality.','result = people.filter("years > 100").select("name")','An empty result does not mean the query failed, but it may signal an unexpected filter.','Explain which schema fields remain when the output has no rows.')]),
('s03','Expressions, nulls, and types','Fundamentals',['spark','spark_sql'],[
('Column expressions','PySpark Column expressions build a distributed computation. Use built-in functions for common transformations instead of bringing data into Python row loops. Name computed fields explicitly.','from pyspark.sql import functions as F\nresult = people.select("name", (F.col("years") + 1).alias("next_year"))','Python boolean operators do not replace the documented Column expression operators.','Construct a filter with two conditions and explain the parentheses.'),
('Null and three-valued logic','A null represents missing or unknown information. Comparisons with null generally yield unknown, so ordinary equality does not select missing values. Use isNull and isNotNull deliberately, and distinguish an empty string from null.','from pyspark.sql import functions as F\nresult = people.filter(F.col("email").isNull()).select("name")','Filtering email == None is not the intended null-test expression.','Predict which rows survive email equality, isNull, and isNotNull.'),
('Conditional expressions','when and otherwise express branching in a column expression. coalesce chooses the first non-null value. Make branch outputs type-compatible and explain any default value as a business rule rather than a technical convenience.','from pyspark.sql import functions as F\nresult = people.select("name", F.coalesce("email", F.lit("missing")).alias("contact"))','Replacing null with zero can change averages and hide missingness.','Choose a display fallback that does not pretend missing data was observed.'),
('Normalize strings and time','Built-in functions can trim whitespace and apply case policies. Timestamp interpretation depends on timezone and parsing conventions. Record the policy with the dataset version so repeated runs produce consistent results.','from pyspark.sql import functions as F\nresult = people.select(F.lower(F.trim("name")).alias("normalized_name"))','Lowercasing every identifier is not universally safe, particularly for case-sensitive keys.','Identify which source values must be preserved alongside their normalized form.')]),
('s04','Joins and aggregations','Fundamentals',['spark','spark_sql'],[
('Join on the intended key','A join combines rows using a condition. Key uniqueness determines whether one input row becomes several output rows. Inspect cardinalities before assuming that a larger output means duplicates should be dropped.','result = people.join(companies, "company_id", "inner").select("name", "company_name")','Joining on a display label can combine unrelated entities with the same name.','Create a duplicate company key and predict the number of joined rows.'),
('Preserve unmatched records','A left join keeps every left-side row and supplies nulls for missing right-side fields. Filters applied afterward can remove those unmatched rows. Decide whether a condition belongs to matching or to final output selection.','result = people.join(companies, "company_id", "left").select("name", "company_name")','Filtering a right-side field after a left join can make it behave like an inner join for those rows.','Show one person without a matching company and retain them.'),
('Aggregate at the right grain','Grouping defines the unit represented by each output row. Count rows, non-null values, or distinct entities according to the question. Join multiplication can inflate totals, so aggregate at the intended grain.','from pyspark.sql import functions as F\nresult = people.groupBy("company_id").agg(F.count("name").alias("people"))','count of a nullable column excludes null values; count of all rows does not.','Compare employee counts with counts of recorded email addresses.'),
('Verify schema and multiplicity','DataFrame correctness includes schema and all row occurrences. Sorting is required only when an order contract exists. A robust test includes duplicates, unmatched keys, and empty inputs rather than checking a single happy-path sample.','result = people.select("name").distinct()','Using distinct to pass one fixture can remove legitimate repeated values in another.','Design a test that distinguishes row counting from distinct-person counting.')]),
('s05','Spark SQL and relational transformations','Intermediate',['spark_sql','spark'],[
('Register and query temporary views','A DataFrame can be registered as a temporary view so Spark SQL and DataFrame code share the same logical plan. Use views for a clear relational expression, then inspect the output schema rather than assuming SQL types.','people.createOrReplaceTempView("staff")\nresult = spark.sql("SELECT company_id, count(*) AS people FROM staff GROUP BY company_id")','A temporary view is scoped to the current Spark session; it is not a durable table.','Write a SQL query that returns one row per company and explain its output grain.'),
('CTEs and grouping levels','A common table expression names an intermediate relation. It is useful when you must aggregate before a later join, because it makes the intended grain visible.','result = spark.sql("WITH experienced AS (SELECT * FROM staff WHERE years >= 3) SELECT company_id, count(*) AS people FROM experienced GROUP BY company_id")','Putting an aggregate after a one-to-many join can silently inflate a count.','Use a CTE to count experienced people before joining a lookup.'),
('Set operations and schema compatibility','UNION ALL preserves repeated rows while UNION removes duplicates. Both sides require compatible columns; make casts and aliases explicit instead of relying on positional coincidence.','result = spark.sql("SELECT name FROM staff WHERE company_id = 1 UNION ALL SELECT name FROM staff WHERE company_id = 2")','UNION is not a join and it does not match rows by key.','Predict the difference between UNION and UNION ALL on repeated names.'),
('SQL semantics and DataFrame equivalence','Spark SQL and the DataFrame API can express the same logical operation. Prefer the form that keeps the transformation, null behavior, and output schema easiest to review.','result = spark.sql("SELECT name, coalesce(email, \'missing\') AS contact FROM staff")','Equivalent-looking SQL and DataFrame expressions can differ when null or type coercion rules differ.','Implement a null-safe contact projection and verify its schema.')]),
('s06','Window functions and deterministic deduplication','Intermediate',['spark_sql','spark'],[
('Partition and order a window','A window keeps individual rows while calculating over a defined partition and order. The partition defines the peer group; the order defines which row is first, last, or cumulative.','from pyspark.sql import Window, functions as F\nw = Window.partitionBy("company_id").orderBy(F.col("years").desc())\nresult = people.withColumn("rank", F.row_number().over(w))','A window without an order is not suitable for choosing a deterministic latest record.','Rank people within each company by experience and state the tie-break rule.'),
('Choose latest records deterministically','Use row_number with a complete ordering to keep exactly one record per business key. Add a stable secondary key whenever timestamps can tie.','from pyspark.sql import Window, functions as F\nw = Window.partitionBy("name").orderBy(F.col("years").desc(), F.col("company_id").asc_nulls_last())\nresult = people.withColumn("rn", F.row_number().over(w)).filter("rn = 1").drop("rn")','dropDuplicates does not express which duplicate should win when records differ.','Keep the latest record per key with an explicit tie-breaker.'),
('Running and moving calculations','Window frames define which ordered rows contribute to an aggregate. A running total uses rows up to the current row; a moving calculation uses a bounded frame.','from pyspark.sql import Window, functions as F\nw = Window.partitionBy("company_id").orderBy("years").rowsBetween(Window.unboundedPreceding, Window.currentRow)\nresult = people.withColumn("running_years", F.sum("years").over(w))','A grouped aggregate collapses rows; a window aggregate preserves them.','Explain when a running total should remain one row per event.'),
('Ranking, ties, and null ordering','row_number breaks ties by order position, rank leaves gaps after ties, and dense_rank does not. Null ordering is part of the contract and should be specified for production deduplication.','from pyspark.sql import Window, functions as F\nw = Window.partitionBy("company_id").orderBy(F.col("years").desc_nulls_last())\nresult = people.withColumn("rank", F.dense_rank().over(w))','Ranking ties without a full ordering can make a chosen winner change across runs.','Compare row_number, rank, and dense_rank on tied values.')]),
('s07','Files, formats, and partitioning','Intermediate',['spark','spark_sql'],[
('Choose a file contract','A file format carries both data and operational tradeoffs. Record schema, timezone, null policy, compression, partition columns, and producer version with each dataset.','result = people.select("company_id", "name", "years")','A directory name that looks partitioned is not proof that every file obeys the same contract.','Define a schema contract for a partitioned workforce snapshot.'),
('Partition for access patterns','Partition columns should match common filters and have manageable cardinality. Too many tiny partitions raise scheduling overhead; too few can force unnecessary reads.','result = people.repartition("company_id").select("company_id", "name")','repartition changes the physical layout for a computation; it does not make a dataset permanently partitioned by itself.','Choose a partition key for daily events queried by date and customer.'),
('Schema evolution deliberately','Additive, nullable columns are usually easier to evolve than renamed or repurposed columns. Read and write behavior must be tested against old and new snapshots.','from pyspark.sql import functions as F\nresult = people.withColumn("source_version", F.lit("v2"))','Automatically merging schemas can hide incompatible type changes.','Describe a safe rollout for a new nullable source field.'),
('Small files and compaction','Many small files create task scheduling overhead and metadata pressure. Compact after measuring file counts and read patterns, while retaining an immutable source snapshot.','result = people.coalesce(1).select("name", "company_id")','coalesce(1) is a debugging tool, not a general production write strategy.','Explain why a single output file can bottleneck a large pipeline.')]),
('s08','Testing and repeatable Spark pipelines','Intermediate',['spark','spark_sql'],[
('Test the contract, not an implementation','A Spark transformation is correct when its schema and row multiset meet the contract. Test empty inputs, nulls, duplicates, and unexpected values in addition to the happy path.','result = people.filter("years >= 0").select("name", "years")','A test that checks only row count can miss a type, nullability, or duplication error.','Write cases that distinguish a valid empty output from a failed transformation.'),
('Idempotent batch processing','A retry-safe batch run produces the intended logical output when the same source snapshot is processed again. Stable record identifiers and explicit replacement or merge rules make this possible.','result = people.dropDuplicates(["name", "company_id"])','Blind deduplication cannot choose correctly when two records with the same key disagree.','State the business key and tie-break rule before adding a deduplication step.'),
('Data quality and quarantine','Separate valid outputs from rows that fail a stated contract. Keep the original row, failure reason, source snapshot, and mapping version so the issue can be corrected and replayed.','from pyspark.sql import functions as F\nresult = people.withColumn("is_valid", F.col("years").isNotNull() & (F.col("years") >= 0))','Silently dropping bad rows removes evidence and makes reconciliation impossible.','Create a validity flag for non-negative recorded experience.'),
('Repeatability and observability','Pin runtime versions, input snapshots, configuration, and timezone. Emit input, valid, rejected, and output counts so a changed run can be explained.','result = people.select("name", "company_id")','A successful job status does not prove the output is complete or at the intended grain.','List the evidence needed to reproduce a batch output.')]),
('s09','Jobs, stages, partitions, and shuffles','Advanced',['spark_perf','spark'],[
('Read an execution plan','A logical plan describes intent; Spark turns it into a physical plan of jobs, stages, and tasks. Wide transformations such as many joins and aggregations often require a shuffle boundary.','result = people.groupBy("company_id").count()','The written order of DataFrame calls is not a reliable account of physical execution.','Inspect a group-by plan and identify where data must be rearranged.'),
('Control partition counts','Partition count is a resource decision. Too few partitions underuse cores; too many make scheduler overhead dominate. Measure records, bytes, skew, and task duration before tuning.','result = people.repartition(2, "company_id").select("name", "company_id")','A fixed partition number copied from another cluster is not a universal tuning setting.','Explain which evidence you would use to change shuffle partitions.'),
('Recognize wide and narrow transformations','A narrow transformation can be computed from one parent partition; a wide one redistributes data. Map, filter, and projection are commonly narrow, while repartition and many groupings are wide.','result = people.filter("years >= 3").repartition("company_id")','A transformation that returns few rows can still be expensive if it shuffles a large input first.','Reorder a filter and repartition after considering semantics and selectivity.'),
('Diagnose skew','Skew occurs when one key or partition has disproportionately more work. Confirm it with task metrics and key distributions before adding salting, repartitioning, or a different join strategy.','result = people.groupBy("company_id").count()','Increasing partitions alone does not divide one hot key across tasks.','Describe a synthetic skew test and the metric that would reveal it.')]),
('s10','Join strategies, skew, caching, and adaptive execution','Advanced',['spark_perf','spark_sql'],[
('Choose joins using evidence','Broadcast joins can avoid shuffling a sufficiently small side. Sort-merge joins and shuffled hash joins have different memory and ordering costs. Use statistics and the physical plan to confirm the selected strategy.','result = people.join(companies, "company_id", "left").select("name", "company_name")','Broadcasting a table just because it was small yesterday can exceed executor memory after growth.','Compare the evidence needed to choose a broadcast lookup versus a shuffle join.'),
('Handle skewed joins','A hot key can make one join task dominate the job. Isolate the skew pattern, then consider adaptive skew handling, selective salting, pre-aggregation, or a different data layout.','result = people.join(companies, "company_id", "left")','Salting every key increases data volume and complexity even when only one key is skewed.','Propose a measurement-driven response to a single hot company key.'),
('Cache only reusable work','Caching trades memory for avoiding repeated computation. Cache after a costly reusable transformation, materialize deliberately, and unpersist when the reuse ends.','result = people.filter("years >= 3").select("name", "company_id")','Caching an input used once can make a job slower through serialization and eviction pressure.','Identify a pipeline branch where caching has a measurable reuse case.'),
('Adaptive query execution','AQE can revise partitioning and join choices from runtime statistics. It improves many workloads but does not replace correct data modeling, skew diagnosis, or plan inspection.','result = people.groupBy("company_id").count()','Assuming AQE always chooses the fastest plan can hide stale statistics or an oversized broadcast.','Record what changed between initial and final plans under AQE.')]),
('s11','Structured Streaming and event-time correctness','Advanced',['spark','spark_sql'],[
('Streaming as incremental tables','Structured Streaming applies a query incrementally to arriving records. Define the output mode, trigger, checkpoint location, and sink semantics as part of the pipeline contract.','result = people.select("name", "company_id")','A streaming source is not automatically exactly-once from producer through every external sink.','Explain the difference between an append output and a complete aggregate output.'),
('Event time and watermarks','Event time is when an event happened; processing time is when the system observed it. A watermark bounds how long state is retained for late data and therefore defines a correctness tradeoff.','result = people.select("name", "years")','A watermark does not guarantee every late record is processed; it limits state based on an allowed lateness policy.','Choose an allowed-lateness policy and explain what data it may exclude.'),
('Duplicates and replay','A restart can replay input. Use stable event IDs, checkpoints, and idempotent sink behavior to make duplicate handling explicit. Do not treat a deduplication operator as proof of end-to-end exactly-once behavior.','result = people.dropDuplicates(["name", "company_id"])','Dropping duplicates by a mutable display name can remove different real events.','Define an event identity and the replay evidence you will retain.'),
('Bounded test streams','Test streaming logic with bounded batches that include late, duplicate, and out-of-order events. Assert output after each batch so changes in state are visible.','result = people.orderBy("company_id", "name")','A one-batch test cannot reveal watermark or restart behavior.','Design three input batches that demonstrate late and duplicate handling.')]),
('s12','Spark deployment and observability','Advanced',['spark_perf','spark'],[
('Package a reproducible job','A production job records Spark version, Python dependencies, configuration, input snapshot, output location, and a stable release identifier. This makes a result explainable after the environment changes.','result = people.select("name", "company_id")','A notebook that ran once interactively is not a reproducible deployment artifact.','List the immutable inputs needed to reproduce a deployed batch run.'),
('Observe the right signals','Monitor input/output counts, rejected rows, stage duration, shuffle bytes, executor memory, retries, and checkpoint health. Tie each alert to an action an operator can take.','result = people.groupBy("company_id").count()','A green job status alone can conceal partial output, skew, or growing cost.','Define an alert for a sudden increase in rejected records.'),
('Recover safely','Recovery begins with an immutable input snapshot and a known-good output version. Design retries to be idempotent, preserve failed artifacts, and promote only a validated complete result.','result = people.filter("years >= 0")','Deleting the prior output before a new run validates leaves no safe rollback point.','Describe how to recover after a failure between staging and publication.'),
('Control cost and access','Set resource limits, least-privilege credentials, storage retention, and budget alerts. Separate development and production data, and keep secrets outside notebooks and submitted code.','result = people.select("name")','Giving every job broad storage access turns a transformation error into a data-loss risk.','Choose the smallest set of permissions needed for a curated-output job.')]),
]

def write(path,text):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(text,encoding='utf-8')

def build_catalog():
    tracks=[{'id':'ontology','title':'Ontology engineering','description':'Model meaning, query knowledge, and build reliable graphs. From RDF fundamentals to production systems.','status':'active','modules':[]},
            {'id':'spark','title':'Apache Spark','description':'Turn data into understanding with PySpark and Spark SQL. Build transformations that you can explain.','status':'active','modules':[]}]
    for mid,title,level,source_keys,units in MODULES:
        sources=[SOURCES[k] for k in source_keys]
        lessons=[]
        for i,(heading,explanation,example,trap,task) in enumerate(units,1):
            lid=f'{mid}-l{i}'
            lessons.append({'id':lid,'title':heading,'minutes':8})
            lang='python' if mid.startswith('s') else 'sparql' if example.startswith(('SELECT','INSERT','DELETE','CLEAR','CONSTRUCT','ASK')) else 'turtle'
            prefix='' if lang=='python' else QP if lang=='sparql' else PREFIX
            text=f'''# {heading}

## What you will be able to do

{task}

## The problem

You are working with workforce and project data that will be used by another team. Your result must have a clear meaning, survive incomplete records, and be reproducible. This lesson focuses on **{heading.lower()}** within {title.lower()}.

## Build the mental model

{explanation}

## Worked example

Read the example before running it. Identify the input facts or columns, the relationship being expressed, and the expected result.

```{lang}
{prefix}{example}
```

## A mistake worth recognizing

> {trap}

Construct a small counterexample that would expose this mistake. Prefer three carefully chosen records to a large dataset whose behavior is hard to explain.

## Predict, then investigate

1. {task}
2. Identify what happens when a relevant value or relationship is missing.
3. Change one fact or row and predict which part of the result changes.
4. Explain the result using the vocabulary introduced above.

## Practice

Open the guided lab in this module to inspect its public fixture and starter file. Then solve an independent exercise from an empty implementation. Compare your output with the requirements, including datatypes, identity, and multiplicity where relevant. If you use a hint or reveal a solution, attempt a fresh variant before claiming independent mastery.

## Takeaway

{explanation.split('. ')[0]}.

## Official references

'''+ '\n'.join(f'- [{s["title"]}]({s["url"]})' for s in sources)+'\n'
            write(ROOT/'lessons'/f'{lid}.md',text)
        module={'id':mid,'number':int(mid[1:]),'title':title,'level':level,'description':' · '.join(u[0] for u in units),'lessons':lessons,'sources':sources,'status':'authored','prerequisites':[] if mid.endswith('01') else [mid[0]+str(int(mid[1:])-1).zfill(2)],'glossary':[{'term':u[0],'definition':u[1].split('. ')[0]+'.'} for u in units]}
        tracks[0 if mid.startswith('o') else 1]['modules'].append(module)
    for tid,title,topics in [
      ('data-engineering','Data engineering',['Storage and formats','Ingestion patterns','Orchestration','Analytical modeling','Batch and streaming','Data quality','Reliability and recovery','Governance']),
      ('sql','SQL',['Filtering and joins','Aggregation','Window functions','Subqueries','Relational modeling','Transactions','Query plans']),
      ('statistics','Statistics for data analysis',['Descriptive statistics','Probability','Sampling','Estimation','Hypothesis testing','Regression','Experimentation'])]:
        tracks.append({'id':tid,'title':title,'description':'A future learning path with a prepared curriculum outline.','status':'planned','modules':[],'topics':topics})
    projects=[]
    for number,pid,title,description,milestones in [
      (1,'workforce','Workforce and project knowledge graph','Connect people, organizations, and assignments with a model whose meaning you can defend.',[
        ('questions','Competency questions','Write six queries the model must support. Include multiple assignments and missing contact details.'),
        ('model','Identity and ontology','Create ontology.ttl and data.ttl with Person, Company, Client, Project, and Assignment. Explain stable identifiers and lifecycle.'),
        ('validation','Queries, shapes, and reasoning','Add executable query examples, positive and negative SHACL fixtures, and intended/unintended OWL entailment checks.'),
        ('review','Explain the model','Document alternatives, limits, and the effect of incomplete data. Export the ontology for an optional Protégé review.')]),
      (2,'commerce','Commerce integration','Reconcile two catalogs and order feeds while retaining the evidence behind every mapping.',[
        ('sources','Source contracts','Create two fixtures with conflicting product names, reused emails, categories, and order-line identifiers.'),
        ('mapping','Mappings and identity','Define stable order and order-line IRIs. Preserve source fields and explain Brand versus Category modeling.'),
        ('resolution','Resolution and quarantine','Create deterministic rules, confidence bands, and a review queue. Record false-merge examples and rejected records.'),
        ('provenance','Reconciliation and evidence','Link canonical facts to source snapshots and mapping activities. Write reconciliation queries and demonstrate reversing a bad match.')]),
      (3,'publication','Reliable knowledge-graph publication','Publish a validated snapshot, recover from failure, and explain query performance with evidence.',[
        ('snapshot','Reproducible snapshot','Record source bytes, versioned mappings, stable identifiers, and expected input/output counts.'),
        ('pipeline','Stage, validate, and publish','Implement staging and quarantine. Promote the complete graph in one dataset transaction.'),
        ('recovery','Failure and recovery','Inject a failure before commit and an ambiguous response after commit. Demonstrate idempotent retries and restoration.'),
        ('performance','Performance and release evidence','Compare equivalent queries with controlled measurements. Record engine version, statistics, limits, and rollback instructions.')])]:
        projects.append({'id':pid,'number':number,'title':title,'description':description,'hours':8 if number==1 else 12,'status':'authored','brief':'Produce a versioned project bundle with your implementation, fixtures, and a short decision record. Use the module workspaces to test each artifact. Milestone notes record self-review evidence; they are not an automated certification of the entire project.','rubric':['The model answers every stated competency question.','Identity, lifecycle, and uncertainty are explicit.','Positive and negative cases are tested.','Results and source evidence can be reproduced.','Tradeoffs and remaining limitations are explained.'],'milestones':[{'id':m[0],'title':m[1],'description':m[2]} for m in milestones],'sources':[SOURCES[k] for k in ['rdf','sparql','owl','shacl','prov']]})
    write(ROOT/'catalog.yaml',yaml.safe_dump({'schema_version':'1','tracks':tracks,'projects':projects},sort_keys=False,allow_unicode=True))

if __name__=='__main__':
    build_catalog()
